#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

key=$(ynh_string_random --length=16)

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression "Configuring PHP-FPM..."

ynh_config_add_phpfpm

ynh_config_add_nginx

ynh_config_add --template="feeds.txt" --destination="$data_dir/feeds.txt"

ynh_config_add --template="cron" --destination="/etc/cron.d/$app"

#=================================================
# INSTALL LYCHEE WITH COMPOSER
#=================================================
ynh_script_progression "Installing RSS with Composer..."

ynh_composer_install
ynh_composer_exec install --no-dev  --no-dev

touch $install_dir/storage/database/database.sqlite

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# FINAL BOOKSTACK INSTALL
#=================================================
ynh_script_progression "Install the app"

pushd $install_dir
	php$php_version artisan key:generate --no-interaction --force
	php$php_version artisan migrate --no-interaction --force
	php$php_version artisan storage:link
	ynh_hide_warnings ynh_exec_as_app npm install
	ynh_hide_warnings ynh_exec_as_app npm run build
popd

# Set permissions to app files
chmod 755 $install_dir
chmod -R o-rwx $install_dir
chown -R $app:www-data $install_dir
chmod 600 $install_dir/.env

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
